---
title: "cog_sci_figs"
output: html_document
---

```{r}
knitr::opts_chunk$set(fig.align='center', echo=FALSE, messages=FALSE, warning = FALSE,
                      fig.height = 3, fig.width=5)

#Load packages + setup
library(rwebppl)
library(tidyverse)
library(ggjoy)
library(directlabels)
library(lme4)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

theme_set(theme_bw(base_size = 14) + theme(panel.grid = element_blank(),
                  strip.background = element_blank()))

seprop <- function(props) {
  mean_prop = mean(props)
  sqrt( (mean_prop*(1 - mean_prop)) / length(props))
}



modality.colors <- c(speak = "#e8250b", point = "#1f11e0", teach ="#54a832", speech = "#e8250b", gesture = "#1f11e0", both ="#54a832")

```

Experiment 1: Gesture-Speech Trade-Off 
```{r}
exp1_data <- read.csv("data/12.8_no_teaching.csv")

exp1_exposures_method <- exp1_data %>%
  ungroup() %>%
  select(condition,subID, exposureRate,method) %>%
  group_by(condition, subID, exposureRate, method) %>%
  summarise(n = n()) %>%
  group_by(condition, subID, exposureRate) %>%
  mutate(n = n/sum(n)) %>%
  ungroup() %>%
  mutate(method = as.factor(method)) %>%
  tidyr::complete(nesting(condition, subID), exposureRate, method, fill = list(n = 0)) %>%
  group_by(condition, method, exposureRate) %>%
  summarise(mean = mean(n), se = seprop(n)) %>%
  ungroup() %>%
  mutate(condition=factor(condition,labels=c('Talk is Cheap', 'Talk is Less Cheap'))) %>%
  mutate(exposureRate=as.factor(exposureRate))

exp1_exposures_method %>% 
  mutate(method=factor(method, labels=c("gesture", "speech"))) %>%
  ggplot(aes(x=exposureRate, y=mean)) +
  geom_point(aes(color=method),size=1.5,position=position_dodge(.25)) +
  geom_line(aes(x=(exposureRate), y=mean, group=interaction(method,condition), color=method),  size=.9,
          position=position_dodge(.25)) +
  geom_linerange(aes(ymax = mean + se,
    ymin = mean - se, color=method), position=position_dodge(.25)) +
  labs(y="Proportion of Trials", x="Exposure Rate during Training") +
  coord_cartesian(ylim=c(0,1)) +
  facet_grid(.~condition) +
  scale_color_manual(values=modality.colors,
    name = "Modality", labels=c("Gesture", "Speech")) +
  scale_fill_manual(values=modality.colors,
    name = "Modality", labels=c("Gesture", "Speech"))
```

Exp1 : Analysis
```{r}
exp1_analysis <- exp1_data %>%
    group_by(subID, exposureRate, targetLabel) %>%
    mutate(appearance = if_else(trialnum == min(trialnum), 1, 2)) %>%
  mutate(appearance= as.numeric(as.factor(appearance))) %>%
  mutate(condition=factor(condition, levels=c("80_50", "100_30")))
# (0, 0, 1)


gm_pretest <- glm(knownAdj ~
                exposureRate,
            data=exp1_analysis,
      family=binomial)

gm <- glm(method ~  condition +
                exposureRate,
            data=exp1_analysis,
      family=binomial)

gm_cont <- glm(method ~  condition +
                exposureRate,
            data=(exp1_analysis %>% filter(knownAdj==1)),
      family=binomial)
```


Exp2: Teaching Plot
```{r}
exp2_data <- read.csv("data/5.12_data_anon.csv") %>%
  group_by(ldf_num, exposureRate, targetObjectName) %>%
  mutate(appearance = if_else(trialnum == min(trialnum), 1,
                              if_else(trialnum == max(trialnum), 3, 2)))

###wrangling data for teaching
prop_methods_teaching <- exp2_data %>%
  filter(toBeDropped != 1) %>%
  ungroup() %>%
  select(condition,ldf_num, partnersExposure, appearance,method) %>%
  group_by(condition, ldf_num,partnersExposure, appearance, method) %>%
  summarise(n = n()) %>%
  group_by(condition, ldf_num,partnersExposure, appearance) %>%
  mutate(n = n/sum(n)) %>%
  ungroup() %>%
  mutate(method = as.factor(method)) %>%
  tidyr::complete(nesting(condition, ldf_num, partnersExposure), appearance, method, fill = list(n = 0)) %>%
  group_by(condition, partnersExposure, method, appearance) %>%
  summarise(mean = mean(n), se = seprop(n)) %>%
  # filter(method=='teach', condition=="100_30") %>%
  ungroup() %>%
  mutate(partnersExposure=factor(partnersExposure, levels=c("None", "Half", "Perfect"), labels=c('None', 'Half', 'Twice'))) %>%
  mutate(appearance=factor(appearance, labels=c('First','Second', 'Third')))

prop_methods_teaching %>%
  filter(method=="label_click") %>%
    mutate(condition=factor(condition,labels=c('Talk is Cheap', 'Talk is Less Cheap'))) %>%
  ggplot(aes(x=appearance, y=mean, label=partnersExposure)) +
  geom_point(aes(x=appearance, y=mean, color=partnersExposure), size=2.25, position=position_dodge(.25)) +
  geom_line(aes(x=appearance, y=mean, group=partnersExposure, color=partnersExposure),
            size=1, position=position_dodge(.25)) +
  geom_linerange(aes(ymax = mean + se,
    ymin = mean - se, color=partnersExposure), position=position_dodge(.25)) +
  facet_grid(.~condition) +
  labs(y="Proportion of Teaching Trials", x="Object Instance during Game") +
  coord_cartesian(ylim=c(0,.6)) +
  geom_dl(aes(label = partnersExposure, color=partnersExposure), method=list("first.qp", hjust=c(.95, 1.45, 1.55), cex = .9)) +
  # scale_color_manual(values=c("#87d868", "#54a832", "#2c6d12"), name=NULL, labels=NULL) 
  scale_color_manual(values=c("#87d868", "#54a832", "#2c6d12"), name = "Partner's Exposure") +
  scale_fill_manual(values=c("#87d868", "#54a832", "#2c6d12"), name = "Partner's Exposure") 

```

Exp2 : Analysis
```{r}
tmp2 <- exp2_data %>%
  filter(toBeDropped != 1) %>%
  mutate(appearance= as.numeric(as.factor(appearance))) %>%
  mutate(partnersExposure = as.numeric(partnersExposure) - 2,
         partnersExposure = if_else(partnersExposure == 2, 1, partnersExposure)) %>%
    mutate(condition=factor(condition, levels=c("80_50", "100_30")))

# (0, 0, 1)

gm_label <- glmer((method=='label') ~ appearance +
                partnersExposure +
                condition +
                exposureRate +
               (exposureRate|ldf_num),
               control = glmerControl(optimizer = "bobyqa"),
            data=tmp2,
      family=binomial)

gm_teach <- glmer((method=='label_click') ~ appearance +
                partnersExposure +
                condition +
                exposureRate +
               (1|ldf_num),
              control = glmerControl(optimizer = "bobyqa"),
            data=tmp2,
      family=binomial)
```



Experiment 3: Implicit Version
```{r}
exp3_data <- read.csv("data/1.26_data.csv")

exp3_dropped <- exp3_data %>%
  filter(toBeDropped != 1) %>%
  group_by(ldf_num, exposureRate, targetObjectName) %>%
  mutate(appearance = if_else(trialnum == min(trialnum), "First",
                              if_else(trialnum == max(trialnum), "Third", "Second"))) %>%
  mutate(method=factor(method, levels=c("label", "click", "label_click"), labels=c('speech', 'gesture', 'teach')))



###wrangling data for plots by exposure
prop_methods_exposures <- exp3_dropped %>%
      mutate(condition=factor(condition, levels=c(40, 30, 20), labels=c('Gesture is Hardest', 'Gesture is Hard', 'Gesture is Easy')))%>%
  filter(toBeDropped != 1) %>%
  # filter(partnersExposure == 0) %>%
  ungroup() %>%
  select(condition,ldf_num, partnersExposure, exposureRate,method) %>%
  group_by(condition, ldf_num,partnersExposure, exposureRate, method) %>%
  summarise(n = n()) %>%
  group_by(condition, ldf_num,partnersExposure, exposureRate) %>%
  mutate(n = n/sum(n)) %>%
  ungroup() %>%
  mutate(method = as.factor(method)) %>%
  tidyr::complete(nesting(condition, ldf_num, partnersExposure), exposureRate, method, fill = list(n = 0)) %>%
  group_by(condition, partnersExposure, method, exposureRate) %>%
  summarise(mean = mean(n), se = seprop(n)) %>%
  ungroup()


#Exp. 3, Plot 1. 
prop_methods_exposures %>% 
  mutate(exposureRate=as.factor(exposureRate)) %>%
  filter(method!="teach", partnersExposure== "Perfect") %>%
  ggplot(aes(x=exposureRate, y=mean, color = method)) +
  geom_point(size=1.5,position=position_dodge(.25)) +
  ## plotting model predictions
  # geom_ribbon(data=(prop_methods_exposures %>% filter(isEmpirical=="pred_perf_teaching")),
  #   aes(x=as.numeric(exposureRate),ymax = mean + se, ymin = mean - se,
  #       fill=method, alpha=.4), position=position_dodge(.25)) +
  geom_line(aes(x=(exposureRate), y=mean, group=interaction(method,condition), color=method),  size=.9,
          position=position_dodge(.25)) +
  geom_linerange(aes(ymax = mean + se,
    ymin = mean - se),position=position_dodge(.25)) +
  coord_cartesian(ylim=c(0,1)) +
  facet_grid(.~condition) +
  scale_color_manual(values=modality.colors)+  
  labs(y="Proportion of Trials", x="Exposure Rate During Training")+
  scale_color_manual(values=c(modality.colors), labels=c("Speech", "Gesture"), name = "Method") 
```




Plot 2: Teaching
```{r}

prop_methods_teaching <- exp3_dropped %>%
  # filter(toBeDropped != 1) %>%
  # filter(partnersExposure == 0) %>%
  ungroup() %>%
  select(condition,ldf_num, partnersExposure, appearance,method) %>%
  group_by(condition, ldf_num,partnersExposure, appearance, method) %>%
  summarise(n = n()) %>%
  group_by(condition, ldf_num,partnersExposure, appearance) %>%
  mutate(n = n/sum(n)) %>%
  ungroup() %>%
  mutate(method = as.factor(method)) %>%
  tidyr::complete(nesting(condition, ldf_num, partnersExposure), appearance, method, fill = list(n = 0)) %>%
  group_by(condition, partnersExposure, method, appearance) %>%
  summarise(mean = mean(n), se = seprop(n)) %>%
  filter(method=='teach') %>%
  ungroup() %>%
  mutate(partnersExposure=factor(partnersExposure, levels=c('None', 'Half', 'Perfect'), labels=c('None', 'Half', 'Double'))) %>%
  mutate(appearance=factor(appearance, labels=c('First','Second', 'Third')))

prop_methods_teaching %>%
  # filter( isEmpirical=='method') %>%
  ggplot(aes(x=appearance, y=mean, label=partnersExposure)) +
  geom_point(aes(x=appearance, y=mean, color=partnersExposure), size=2.25, position=position_dodge(.25)) +
  # geom_ribbon(data=(prop_methods_teaching %>% filter(isEmpirical=="pred_perf_teaching")),
  #   aes(x=as.numeric(appearance),ymax = mean + se, ymin = mean - se, 
  #       fill=partnersExposure, alpha=.4), position=position_dodge(.25)) +
  geom_line(aes(x=appearance, y=mean, group=partnersExposure, color=partnersExposure), 
            size=1, position=position_dodge(.25)) +
  geom_linerange(aes(ymax = mean + se,
    ymin = mean - se, color=partnersExposure), position=position_dodge(.25)) +
  facet_grid(. ~ condition) +
  labs(y="Proportion of Teaching Trials", x="Object Instance during Game") +
  coord_cartesian(ylim=c(0,.4)) +
  # geom_dl(aes(label = partnersExposure, color=partnersExposure), method=list("first.qp", hjust=c(.95, 1.45, 1.55), cex = .9))+
  # scale_color_manual(values=c("#87d868", "#54a832", "#2c6d12"), name=NULL, labels=NULL) 
  scale_color_manual(values=c("#87d868", "#54a832", "#2c6d12"), name = "Partner's Exposure", 
                    labels=c("None", "Half as Much", "Twice as Much")) +
  scale_fill_manual(values=c("#87d868", "#54a832", "#2c6d12"), name = "Partner's Exposure", 
                    labels=c("None", "Half as Much", "Twice as Much")) 
```




Exp3 : Analysis
```{r}
tmp <- exp3_dropped %>%
  filter(toBeDropped==0) %>%
  mutate(appearance= as.numeric(as.factor(appearance))) %>%
  mutate(partnersExposure = as.numeric(partnersExposure) - 2,
         partnersExposure = if_else(partnersExposure == 2, 1, partnersExposure))
# (0, 0, 1)

gm_label <- glmer((method=='speech') ~ appearance *
                partnersExposure +
                condition +
                exposureRate +
               (exposureRate|ldf_num),
               control = glmerControl(optimizer = "bobyqa"),
            data=tmp,
      family=binomial)

gm_teach <- glmer((method=='teach') ~ appearance +
                partnersExposure +
                condition +
                exposureRate +
               (exposureRate|ldf_num),
            data=tmp,
      family=binomial)
```


